//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Client.IISHostServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class JobDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobLocation {
            get {
                return this.JobLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.JobLocationField, value) != true)) {
                    this.JobLocationField = value;
                    this.RaisePropertyChanged("JobLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName {
            get {
                return this.JobNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNameField, value) != true)) {
                    this.JobNameField = value;
                    this.RaisePropertyChanged("JobName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Skill {
            get {
                return this.SkillField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillField, value) != true)) {
                    this.SkillField = value;
                    this.RaisePropertyChanged("Skill");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISHostServiceReference.IJobOpening")]
    public interface IJobOpening {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpening/GetOpeningJobs", ReplyAction="http://tempuri.org/IJobOpening/GetOpeningJobsResponse")]
        WCF_Client.IISHostServiceReference.JobDetails[] GetOpeningJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpening/GetOpeningJobs", ReplyAction="http://tempuri.org/IJobOpening/GetOpeningJobsResponse")]
        System.Threading.Tasks.Task<WCF_Client.IISHostServiceReference.JobDetails[]> GetOpeningJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpening/GetOpeningJobsByRole", ReplyAction="http://tempuri.org/IJobOpening/GetOpeningJobsByRoleResponse")]
        WCF_Client.IISHostServiceReference.JobDetails GetOpeningJobsByRole(string Role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpening/GetOpeningJobsByRole", ReplyAction="http://tempuri.org/IJobOpening/GetOpeningJobsByRoleResponse")]
        System.Threading.Tasks.Task<WCF_Client.IISHostServiceReference.JobDetails> GetOpeningJobsByRoleAsync(string Role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobOpeningChannel : WCF_Client.IISHostServiceReference.IJobOpening, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobOpeningClient : System.ServiceModel.ClientBase<WCF_Client.IISHostServiceReference.IJobOpening>, WCF_Client.IISHostServiceReference.IJobOpening {
        
        public JobOpeningClient() {
        }
        
        public JobOpeningClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobOpeningClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobOpeningClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobOpeningClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Client.IISHostServiceReference.JobDetails[] GetOpeningJobs() {
            return base.Channel.GetOpeningJobs();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.IISHostServiceReference.JobDetails[]> GetOpeningJobsAsync() {
            return base.Channel.GetOpeningJobsAsync();
        }
        
        public WCF_Client.IISHostServiceReference.JobDetails GetOpeningJobsByRole(string Role) {
            return base.Channel.GetOpeningJobsByRole(Role);
        }
        
        public System.Threading.Tasks.Task<WCF_Client.IISHostServiceReference.JobDetails> GetOpeningJobsByRoleAsync(string Role) {
            return base.Channel.GetOpeningJobsByRoleAsync(Role);
        }
    }
}
